name: 'tocaboca_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  tocaboca_analytics:
    # Persisting documentation to write to databricks catalog
    +persist_docs:
      relation: true
      columns: true
    silver:
      +meta:
        owner: "Data team"
      +materialized: table
      +catalog: |
        {%- if target.name == "prod" -%} prod_silver
        {%- else -%} sandbox
        {%- endif -%}
    gold:
      +meta:
        owner: "Data team"
      +materialized: table
      +catalog: |
        {%- if target.name == "prod" -%} prod_gold
        {%- else -%} sandbox
        {%- endif -%}
